"""Initial migration.

Revision ID: 35e8ae055fea
Revises: 
Create Date: 2021-03-14 12:07:19.328312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e8ae055fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('Recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('Unit',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('RecipeIngredient',
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.recipe_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['Unit.unit_id'], ),
    sa.PrimaryKeyConstraint('recipe_ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecipeIngredient')
    op.drop_table('Unit')
    op.drop_table('Recipe')
    op.drop_table('Ingredient')
    # ### end Alembic commands ###
